//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 09:34:39 AM MEZ 
//


package datalog;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Or-inner.type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Or-inner.type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;group ref="{http://www.ruleml.org/1.0/xsd}Or.content"/>
 *       &lt;attGroup ref="{http://www.ruleml.org/1.0/xsd}Or-inner.attlist"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Or-inner.type", propOrder = {
    "oid",
    "formulaOrAtomOrAnd"
})
public class OrInnerType {

    protected OidType oid;
    @XmlElements({
        @XmlElement(name = "Or", type = OrInnerType.class),
        @XmlElement(name = "Atom", type = AtomType.class),
        @XmlElement(name = "formula", type = FormulaAndOrType.class),
        @XmlElement(name = "And", type = AndInnerType.class)
    })
    protected List<Object> formulaOrAtomOrAnd;

    /**
     * Gets the value of the oid property.
     * 
     * @return
     *     possible object is
     *     {@link OidType }
     *     
     */
    public OidType getOid() {
        return oid;
    }

    /**
     * Sets the value of the oid property.
     * 
     * @param value
     *     allowed object is
     *     {@link OidType }
     *     
     */
    public void setOid(OidType value) {
        this.oid = value;
    }

    /**
     * Gets the value of the formulaOrAtomOrAnd property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the formulaOrAtomOrAnd property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFormulaOrAtomOrAnd().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrInnerType }
     * {@link AtomType }
     * {@link FormulaAndOrType }
     * {@link AndInnerType }
     * 
     * 
     */
    public List<Object> getFormulaOrAtomOrAnd() {
        if (formulaOrAtomOrAnd == null) {
            formulaOrAtomOrAnd = new ArrayList<Object>();
        }
        return this.formulaOrAtomOrAnd;
    }

}
