//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.14 at 09:34:39 AM MEZ 
//


package datalog;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for if-entails.type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="if-entails.type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;group ref="{http://www.ruleml.org/1.0/xsd}if-entails.content"/>
 *       &lt;attGroup ref="{http://www.ruleml.org/1.0/xsd}if.attlist"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "if-entails.type", propOrder = {
    "rulebase"
})
public class IfEntailsType {

    @XmlElement(name = "Rulebase")
    protected RulebaseType rulebase;

    /**
     * Gets the value of the rulebase property.
     * 
     * @return
     *     possible object is
     *     {@link RulebaseType }
     *     
     */
    public RulebaseType getRulebase() {
        return rulebase;
    }

    /**
     * Sets the value of the rulebase property.
     * 
     * @param value
     *     allowed object is
     *     {@link RulebaseType }
     *     
     */
    public void setRulebase(RulebaseType value) {
        this.rulebase = value;
    }

}
