package ruleml.test.translator

import ruleml.test.translator.datamodel.*;

rule "test1"
when
	Buy($b:buyer == "John", $i:item)
	Keep(keeper == $b, item == $i)
then
	insert( new Own($i, $b));
end

rule "facts"
then
	insert(new Buy("John", "laptop", "Amazon"));
	insert(new Keep("John","laptop"));
	insert(new Buy("Mary", "camcorder", "Ebay"));
	insert(new Keep("Mary","camcorder"));
	insert(new Buy("John", "phone", "Ebay"));
end

/*
rule "test2"
when
	$p : Person ( name=="Tisho" )
	$b : Buy (buyer==$p, $s:seller, $i:item=="Object")
	Keep (keeper==$p, item==$i)
then
	retract ($b);
end
*/